# Travis CI configuration file for psycopg2

dist: trusty
sudo: required
language: python

python:
  - 3.7-dev
  - 2.7
  - 3.6
  - 3.5
  - 3.4

install:
  - pip install -U pip setuptools wheel
  - pip install .
  - rm -rf psycopg2.egg-info
  - sudo scripts/travis_prepare.sh

script:
  - scripts/travis_test.sh

notifications:
  email: false
